<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Gioithieu.aspx.cs" Inherits="Gioithieu" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
            background-color: #FFFFFF;
        }
        .auto-style2 {
            width: 510px;
            background-color: #FFFFFF;
        }
        .auto-style3 {
            font-size: large;
        }
        .auto-style4 {
            font-size: xx-large;
            color: #0099FF;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <label><center class="auto-style4"><strong>GIỚI THIỆU</strong></center></label>
    <table class="auto-style1">
        <tr>
            <td class="auto-style2">
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <span class="auto-style3">N</span>ăm năm sau ngày đất nước thống nhất, phong trào thanh thiếu nhi thành phố đã có những bước phát triển vượt bậc cả về số lượng và chất lượng, công việc giáo dục thanh thiếu nhi cần thêm nhiều tài liệu thiết thực, bổ ích, phù hợp với yêu cầu phát triển của địa phương trong tình hình mới, được sự quan tâm lãnh đạo và chỉ đạo của Thành ủy, một số cán bộ Đoàn tâm huyết với việc giáo dục thanh thiếu nhi qua các xuất bản phẩm của Thành đoàn được phân công chuẩn bị lực lượng để thành lập một NXB, trước mắt là in sách phục vụ cho phong trào thiếu nhi thành phố. Trên tinh thần đó, ngày 24-3-1981 UBND Huế đã ký quyết định thành lập Nhà xuất bản Măng Non trực thuộc Thành đoàn TP.Huế.</p>
                <p style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <span style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 0px; line-height: 1.6em; background-color: #FFFFFF;">Sau gần năm năm hoạt động với nhiều nỗ lực và hiệu quả, ngày 3-2-1986, NXB Măng Non được UBND&nbsp;TP.Huế ký quyết định đổi tên thành Hueic BookStore với chức năng và nhiệm vụ được mở rộng là đơn&nbsp;vị&nbsp;xuất bản dành cho thanh thiếu nhi thành phố và khu vực Trung bộ.</span></p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Có thể nói từ khi thành lập đến nay, với tinh thần của những cán bộ Đoàn hoạt động trên lĩnh vực xuất bản, các thế hệ cán bộ nhân viên Hueic BookStore đã đưa hoạt động của NXB ngày càng phát triển, tạo nên uy tín vững vàng trong lòng bạn đọc, không những ở thành phố Hồ Chí Minh và khu vực Nam bộ mà còn mở rộng ra cả trong nước và ngoài nước. Những năm gần đây, Hueic BookStore luôn là một trong những thương hiệu dẫn đầu trên cả nước trong lĩnh vực xuất bản.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Ngay từ ngày đầu thành lập, đội ngũ Hueic BookStore đã khẳng định tiêu chí làm sách của mình là làm sách để nuôi dưỡng tâm hồn, khơi nguồn tri thức cho bạn đọc. Với tinh thần này, Trẻ đã không ngừng giới thiệu cho bạn đọc trước hết là ở thành phố và trong cả nước những tác phẩm văn học có giá trị dành cho thanh thiếu nhi, những cuốn sách về kỹ năng hoạt động Đoàn, Hội, Đội dành cho cán bộ hoạt động phong trào, và những tác phẩm nhiều thể loại, đề tài liên quan đến việc tăng cường tri thức và kỹ năng sống.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Bên cạnh việc thực hiện chức năng nhiệm vụ giáo dục chính trị truyền thống bằng xuất bản phẩm, NXB còn cung cấp cho bạn đọc nhiều đầu sách giải trí và tăng cường tri thức có giá trị khác. Hueic BookStore cũng là đơn vị đi đầu trong cả nước về việc giao dịch tác quyền với nước ngoài trong giai đoạn hội nhập và đã giới thiệu với bạn đọc Việt Nam nhiều bộ sách của các tác giả thế giới có giá trị nhiều mặt.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Khi ngành xuất bản trong nước lâm vào giai đoạn khó khăn trong những năm cuối thập niên 80 đầu 90 thế kỷ 20, Hueic BookStore cũng là đơn vị đi đầu trong việc liên kết xuất bản với các cá nhân và đơn vị khác nhằm cung cấp cho bạn đọc nhiều đầu sách mà khả năng khai thác và đầu tư của Hueic BookStore không thể đảm bảo được. Ngay trong giai đoạn phát triển nhất của việc liên kết xuất bản, Hueic BookStore đã nhanh chóng đầu tư vào việc khai thác sách theo kế hoạch A, tức là loại sách mà chính NXB đầu tư cả công sức và tiền của, tự mở rộng mạng lưới phát hành và từng bước đưa sản lượng sách kế hoạch A trở thành lượng sách chủ đạo của NXB với tỉ lệ từ 20-30% từ những năm cuối thập niên 90 lên 70-80% trong những năm gần đây.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Bằng việc giới thiệu với bạn đọc trong cả nước những tác phẩm có bản quyền của tác giả Việt Nam và thế giới, NXB đã từng bước khẳng định phương cách làm ăn đàng hoàng và có uy tín của mình. Từ những bộ truyện tranh nổi tiếng trên thế giới như Lucky Luke, Spirou và Fantasio... đến những bộ truyện chữ như Harry Potter và Chạng Vạng... của thế giới, từ việc mua tác quyền trọn đời và giới thiệu với bạn đọc toàn bộ sách Sơn Nam, Nguyễn Văn Hầu, hay một phần sách của các<span class="Apple-converted-space">&nbsp;</span></p>
            </td>
            <td>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    nhà nghiên cứu Nguyễn Đổng Chi, Toan Ánh..., đến các cuộc thi sáng tác văn học Vì tương lai đất nước dành cho thiếu nhi và Văn học tuổi 20 dành cho thanh niên, NXB từng bước đã trở thành vườn ươm cho các cây bút trẻ...</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Dù làm ít hay nhiều sách trong một năm, tiêu chí hàng đầu mà Hueic BookStore luôn nêu cao là chất lượng, chất lượng và chất lượng, cho dù là sách do mình tự làm, hay là sách liên doanh, liên kết. Cũng từ tiêu chí này mà bạn đọc dần dần nhận ra giá trị mà thương hiệu Trẻ xây dựng trong suốt quá trình hoạt động xuất bản của mình.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Với nội dung phong phú trên nhiều lĩnh vực, gắn với tôn chỉ mục đích là phục vụ cho thanh thiếu nhi, tổ chức Đoàn các cấp và bạn đọc rộng rãi, các xuất bản phẩm của Hueic BookStore được chăm chút cẩn thận từ hình thức đến nội dung và không ngừng đổi mới trên tinh thần cầu thị, tôn trọng bạn đọc. Có thể kể một số tủ sách, tựa sách đã đi vào tâm thức bạn đọc, góp phần tạo nên thương hiệu Hueic BookStore như: bộ sách Lịch sử Việt Nam bằng tranh, tủ sách Khoa học Khám phá, các tác phẩm của nhà văn lão thành Sơn Nam, Vương Hồng Sển, Toan Ánh, Nguyễn Văn Hầu, các nhà văn trưởng thành sau ngày giải phóng như: Bảo Ninh, Nguyễn Nhật Ánh, Nguyễn Ngọc Tư, Dương Thụy, Nguyễn Ngọc Thuần…, các tủ sách Kỹ năng Đoàn Đội, Cánh cửa mở rộng, Văn học trong nhà trường, các tựa sách dành cho lứa tuổi mầm non – đặc biệt là loạt truyện BuBu, những tựa sách về chính trị truyền thống được chăm chút cẩn thận từ nội dung đến mỹ thuật như 1000 năm Thăng Long – Hà Nội, Võ Văn Kiệt – Người thắp lửa, Võ Nguyên Giáp – Người yêu 
                    nước, Người thầy, Người lính,…</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Nhiều tác phẩm do Hueic BookStore xuất bản đã đoạt được các giải thưởng lớn như Giải thưởng Văn học ASEAN (Cơn giông – Lê Văn Thảo, Cánh đồng bất tận – Nguyễn Ngọc Tư, Cho tôi xin một vé đi tuổi thơ – Nguyễn Nhật Ánh), Giải thưởng Hội Nhà văn Việt Nam qua các năm (Một ngày và một đời – Lê Văn Thảo, Dũng Sài Gòn – Nguyễn Trí Công, Một chuyến đi xa – Đào Hiếu, Cánh đồng bất tận – Nguyễn Ngọc Tư, Cho tôi xin một vé đi tuổi thơ – Nguyễn Nhật Ánh…), Giải thưởng Peter Pan 2008 của Ủy ban quốc tế về sách dành cho thiếu nhi tại Thụy Điển (Vừa nhắm mắt vừa mở cửa sổ - Nguyễn Ngọc Thuần)… Các cuộc vận động sáng tác văn học lớn do Hueic BookStore phối hợp báo Tuổi Trẻ, Hội Nhà văn TP.Huế tổ chức như: Giải thưởng Văn học tuổi 20 và Giải Văn học thiếu nhi Vì tương lai đất nước (phối hợp với Hội Nhà văn TP.Huế) đều tạo được uy tín lớn trong xã hội, góp phần phát hiện và nuôi dưỡng nhiều cây bút tài hoa như Nguyên Hương, Nguyễn Ngọc Tư, Nguyễn Ngọc Thuần, Phong Điệp, Phan Triều Hải…</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Ngày 29-5-2012 , Công ty TNHH sách điện tử Trẻ (Ybook) thuộc Hueic BookStore được thành lập, tạo ra bước ngoặt mới cho thị trường sách số vốn đã xuất hiện thầm lặng tại Việt Nam trong nhiều năm. Việc khai thác e-book tại Hueic BookStore không chỉ tạo điều kiện thuận lợi cho việc công bố các tác phẩm mới, mà còn hỗ trợ cho cả những tác phẩm đã xuất bản và lưu hành trên thị trường Việt Nam.</p>
                <p align="left" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; box-sizing: border-box; list-style: none; outline: 0px; padding: 3px 0px; orphans: 3; widows: 3; color: rgb(85, 85, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Nhà xuất bản Trẻ đã vinh dự được đón nhận Huân chương Lao động hạng Nhất cùng nhiều bằng khen, giấy khen, danh hiệu khác. Cùng với sự yêu quý, tin tưởng của các tác giả, cộng tác viên và đặc biệt là hàng triệu bạn đọc, Hueic BookStore luôn nỗ lực mang đến những món ăn tinh thần phong phú và bổ ích nhất. Năng động, sáng tạo, dám nghĩ, dám làm, Hueic BookStore tự hào được đồng hành với xã hội Nuôi dưỡng tâm hồn – Khơi nguồn tri thức, mở ra không chỉ những trang sách mà còn là những chân trời bát ngát cho bạn đọc thân yêu của mình.</p>
            </td>
        </tr>
    </table>
</asp:Content>

